// exames_ref.js
// VERSÃO: 1.0.0 (exames_ref.js)
// CHANGELOG:
// - NOVO: Arquivo criado para conter o objeto EXAM_DETAILS, centralizando unidades e valores de referência.

export const EXAM_DETAILS = {
    "Hemograma Completo": { defaultUnit: "N/A", referenceRange: { general: "Varia (Texto Livre)" }, inputType: "text" },
    "Glicemia": { defaultUnit: "mg/dL", referenceRange: { general: "< 99 mg/dL" }, inputType: "text" },
    "Colesterol Total": { defaultUnit: "mg/dL", referenceRange: { general: "< 190 mg/dL" }, inputType: "text" },
    "Colestetol Total e Frações": { defaultUnit: "mg/dL", referenceRange: { general: "< 190 mg/dL" }, inputType: "text" }, // Adicionado para match exato
    "Triglicerídeos": { defaultUnit: "mg/dL", referenceRange: { general: "< 150 mg/dL" }, inputType: "text" },
    "Ureia": { defaultUnit: "mg/dL", referenceRange: { general: "15 - 45 mg/dL" }, inputType: "text" },
    "Ureia (BUN)": { defaultUnit: "mg/dL", referenceRange: { general: "15 - 45 mg/dL" }, inputType: "text" }, // Adicionado para match exato
    "Creatinina": { defaultUnit: "mg/dL", referenceRange: { male: "0.7 - 1.2 mg/dL", female: "0.5 - 0.9 mg/dL" }, inputType: "text" },
    "Creatinina (Creat)": { defaultUnit: "mg/dL", referenceRange: { male: "0.7 - 1.2 mg/dL", female: "0.5 - 0.9 mg/dL" }, inputType: "text" }, // Adicionado para match exato
    "Exame de Urina": { defaultUnit: "N/A", referenceRange: { general: "Normal" }, inputType: "select", options: ["Normal", "Anormal"] },
    "Urina Tipo I (EAS)": { defaultUnit: "N/A", referenceRange: { general: "Normal" }, inputType: "select", options: ["Normal", "Anormal"] },
    "Sumário de Urina": { defaultUnit: "N/A", referenceRange: { general: "Normal" }, inputType: "select", options: ["Normal", "Anormal"] },
    "TSH": { defaultUnit: "µUI/mL", referenceRange: { general: "0.4 - 4.0 µUI/mL" }, inputType: "text" },
    "T4 Livre": { defaultUnit: "ng/dL", referenceRange: { general: "0.8 - 1.9 ng/dL" }, inputType: "text" },
    "Vitamina D": { defaultUnit: "ng/mL", referenceRange: { general: "30 - 100 ng/mL" }, inputType: "text" },
    "Ácido Úrico": { defaultUnit: "mg/dL", referenceRange: { male: "3.5 - 7.2 mg/dL", female: "2.6 - 6.0 mg/dL" }, inputType: "text" },
    "Bilirrubinas": { defaultUnit: "mg/dL", referenceRange: { general: "Total: < 1.2 mg/dL" }, inputType: "text" },
    "Ferro Sérico": { defaultUnit: "µg/dL", referenceRange: { general: "60 - 170 µg/dL" }, inputType: "text" },
    "Gama GT": { defaultUnit: "U/L", referenceRange: { male: "11 - 50 U/L", female: "7 - 32 U/L" }, inputType: "text" },
    "PCR (Proteína C Reativa)": { defaultUnit: "mg/L", referenceRange: { general: "< 5 mg/L" }, inputType: "text" },
    "Cálcio": { defaultUnit: "mg/dL", referenceRange: { general: "8.5 - 10.2 mg/dL" }, inputType: "text" },
    "Cálcio Total (Ca Total)": { defaultUnit: "mg/dL", referenceRange: { general: "8.5 - 10.2 mg/dL" }, inputType: "text" },
    "Potássio": { defaultUnit: "mEq/L", referenceRange: { general: "3.5 - 5.1 mEq/L" }, inputType: "text" },
    "Sódio": { defaultUnit: "mEq/L", referenceRange: { general: "136 - 145 mEq/L" }, inputType: "text" },
    "Magnésio": { defaultUnit: "mg/dL", referenceRange: { general: "1.7 - 2.2 mg/dL" }, inputType: "text" },
    "TGO (AST)": { defaultUnit: "U/L", referenceRange: { general: "Até 35 U/L" }, inputType: "text" },
    "TGP (ALT)": { defaultUnit: "U/L", referenceRange: { general: "Até 35 U/L" }, inputType: "text" },
    "Fator Reumatoide (FR)": { defaultUnit: "UI/mL", referenceRange: { general: "< 14 UI/mL" }, inputType: "text" },
    "VHS (Velocidade de Hemossedimentação)": { defaultUnit: "mm/h", referenceRange: { general: "Varia com idade e sexo" }, inputType: "text" },
    "FAN (Fator Antinúcleo)": { defaultUnit: "N/A", referenceRange: { general: "Não Reagente" }, inputType: "select", options: ["Não Reagente", "Reagente"] },
    "HDL-Colesterol (Colesterol de Alta Densidade)": { defaultUnit: "mg/dL", referenceRange: { general: "> 40 mg/dL" }, inputType: "text" },
    "LDL-Colesterol (Colesterol de Baixa Densidade)": { defaultUnit: "mg/dL", referenceRange: { general: "< 130 mg/dL (ótimo <100)" }, inputType: "text" },
    "Urocultura (Cultura de Urina)": { defaultUnit: "UFC/mL", referenceRange: { general: "< 10.000 UFC/mL (Negativa)" }, inputType: "select", options: ["Negativa", "Positiva"] },
    "Fosfatase Alcalina (FA)": { defaultUnit: "U/L", referenceRange: { general: "40 - 129 U/L" }, inputType: "text" },
    "Cloro (Cl)": { defaultUnit: "mEq/L", referenceRange: { general: "98 - 107 mEq/L" }, inputType: "text" },
    "Ácido Fólico (Folato)": { defaultUnit: "ng/mL", referenceRange: { general: "3.1 - 17.5 ng/mL" }, inputType: "text" },
    "Ferritina (Ferr)": { defaultUnit: "ng/mL", referenceRange: { male: "20 - 300 ng/mL", female: "10 - 150 ng/mL" }, inputType: "text" },
    "Vitamina B12 (Cobalamina)": { defaultUnit: "pg/mL", referenceRange: { general: "200 - 900 pg/mL" }, inputType: "text" },
    "Proteínas Totais e Frações (PTF)": { defaultUnit: "g/dL", referenceRange: { general: "Total: 6.0 - 8.0 g/dL" }, inputType: "text" },
    "Parasitológico de Fezes (EPF)": { defaultUnit: "N/A", referenceRange: { general: "Negativo" }, inputType: "select", options: ["Negativo", "Positivo"] },
    "Pesquisa de Sangue Oculto nas Fezes (PSOMF)": { defaultUnit: "N/A", referenceRange: { general: "Negativo" }, inputType: "select", options: ["Negativo", "Positivo"] },
    "Cultura de Fezes (Coprocultura)": { defaultUnit: "N/A", referenceRange: { general: "Negativa" }, inputType: "select", options: ["Negativa", "Positiva"] },
    "Peptídeo Natriurético Cerebral (BNP)": { defaultUnit: "pg/mL", referenceRange: { general: "< 100 pg/mL" }, inputType: "text" },
    "Eletroforese de Proteínas (Eletroforese)": { defaultUnit: "N/A", referenceRange: { general: "Padrão Normal" }, inputType: "text" },
    "Chumbo (Pb)": { defaultUnit: "µg/dL", referenceRange: { general: "< 10 µg/dL" }, inputType: "text" },
    "Cromo (Cr)": { defaultUnit: "µg/L", referenceRange: { general: "< 1.0 µg/L" }, inputType: "text" },
    "Fator V Leiden (FVL)": { defaultUnit: "N/A", referenceRange: { general: "Negativo" }, inputType: "select", options: ["Negativo", "Positivo"] },
    "D-Dímero (D-Dimer)": { defaultUnit: "ng/mL FEU", referenceRange: { general: "< 500 ng/mL FEU" }, inputType: "text" },
    "Tempo de Protrombina (TP)": { defaultUnit: "Segundos", referenceRange: { general: "10 - 14 Segundos" }, inputType: "text" },
    "Tempo de Tromboplastina Parcial Ativada (TTPA)": { defaultUnit: "Segundos", referenceRange: { general: "25 - 35 Segundos" }, inputType: "text" },
    "Pesquisa de Malária (Gota Espessa)": { defaultUnit: "N/A", referenceRange: { general: "Negativa" }, inputType: "select", options: ["Negativa", "Positiva"] },
    "Apolipoproteína A1 (ApoA1)": { defaultUnit: "mg/dL", referenceRange: { male: "100 - 190 mg/dL", female: "120 - 220 mg/dL" }, inputType: "text" },
    "Apolipoproteína B (ApoB)": { defaultUnit: "mg/dL", referenceRange: { general: "< 120 mg/dL" }, inputType: "text" },
    "Estradiol (E2)": { defaultUnit: "pg/mL", referenceRange: { general: "Varia com fase do ciclo" }, inputType: "text" },
    "Progesterona (Prog)": { defaultUnit: "ng/mL", referenceRange: { general: "Varia com fase do ciclo" }, inputType: "text" },
    "LH (Hormônio Luteinizante)": { defaultUnit: "mUI/mL", referenceRange: { general: "Varia com fase do ciclo" }, inputType: "text" },
    "FSH (Hormônio Folículo Estimulante)": { defaultUnit: "mUI/mL", referenceRange: { general: "Varia com fase do ciclo" }, inputType: "text" },
    "Prolactina (PRL)": { defaultUnit: "ng/mL", referenceRange: { general: "< 25 ng/mL" }, inputType: "text" },
    "PSA Total (Antígeno Prostático Específico Total)": { defaultUnit: "ng/mL", referenceRange: { general: "< 4.0 ng/mL (Varia com idade)" }, inputType: "text" },
    "PSA Livre (Antígeno Prostático Específico Livre)": { defaultUnit: "ng/mL", referenceRange: { general: "Proporção PSA L/T > 0.15" }, inputType: "text" },
    "Testosterona Total (Testo Total)": { defaultUnit: "ng/dL", referenceRange: { male: "240 - 950 ng/dL", female: "8 - 60 ng/dL" }, inputType: "text" },
    "Testosterona Livre (Testo Livre)": { defaultUnit: "pg/mL", referenceRange: { male: "50 - 210 pg/mL", female: "0.5 - 8.0 pg/mL" }, inputType: "text" },
    "Transferrina (Transf)": { defaultUnit: "mg/dL", referenceRange: { general: "200 - 400 mg/dL" }, inputType: "text" },
    "Fenitoína (Difenil-hidantoína)": { defaultUnit: "µg/mL", referenceRange: { general: "10 - 20 µg/mL" }, inputType: "text" },
    "Ácido Valproico (Valproato)": { defaultUnit: "µg/mL", referenceRange: { general: "50 - 100 µg/mL" }, inputType: "text" },
    "HBsAg (Antígeno de Superfície da Hepatite B)": { defaultUnit: "N/A", referenceRange: { general: "Não Reagente" }, inputType: "select", options: ["Não Reagente", "Reagente"] },
    "Anti-HCV (Anticorpo Anti-Hepatite C)": { defaultUnit: "N/A", referenceRange: { general: "Não Reagente" }, inputType: "select", options: ["Não Reagente", "Reagente"] },
    "VDRL (Sífilis)": { defaultUnit: "N/A", referenceRange: { general: "Não Reagente" }, inputType: "select", options: ["Não Reagente", "Reagente"] },
    "FTA-Abs (Sífilis (Teste Confirmatório))": { defaultUnit: "N/A", referenceRange: { general: "Não Reagente" }, inputType: "select", options: ["Não Reagente", "Reagente"] },
    "Pesquisa de BAAR (Bacilo Álcool-Ácido Resistente)": { defaultUnit: "N/A", referenceRange: { general: "Negativo" }, inputType: "select", options: ["Negativo", "Positivo"] },
    "Pesquisa de Tuberculose (Cultura para TB)": { defaultUnit: "N/A", referenceRange: { general: "Negativa" }, inputType: "select", options: ["Negativa", "Positiva"] },
    "Beta-HCG (HCG Quantitativo)": { defaultUnit: "mUI/mL", referenceRange: { general: "Varia (Gravidez)" }, inputType: "text" },
    "Pesquisa de Fungos (Micológico Direto)": { defaultUnit: "N/A", referenceRange: { general: "Negativo" }, inputType: "select", options: ["Negativo", "Positivo"] },
    "Pesquisa de Leishmania (Leishmania)": { defaultUnit: "N/A", referenceRange: { general: "Negativa" }, inputType: "select", options: ["Negativa", "Positiva"] },
    "Alfa-1 Glicoproteína Ácida (AGP)": { defaultUnit: "mg/dL", referenceRange: { general: "50 - 120 mg/dL" }, inputType: "text" },
    "Alfa-Fetoproteína (AFP)": { defaultUnit: "ng/mL", referenceRange: { general: "< 10 ng/mL" }, inputType: "text" },
    "Bacterioscopia (Gram)": { defaultUnit: "N/A", referenceRange: { general: "Negativa" }, inputType: "select", options: ["Negativa", "Positivo"] },
    "Lítio (Li)": { defaultUnit: "mEq/L", referenceRange: { general: "0.6 - 1.2 mEq/L" }, inputType: "text" },
    "Troponina I (TnI)": { defaultUnit: "ng/mL", referenceRange: { general: "< 0.04 ng/mL" }, inputType: "text" },
    "Painel Viral Respiratório (PCR Viral)": { defaultUnit: "N/A", referenceRange: { general: "Negativo" }, inputType: "select", options: ["Negativo", "Positivo"] },
    "Microalbuminúria (MAU)": { defaultUnit: "mg/24h", referenceRange: { general: "< 30 mg/24h" }, inputType: "text" },
    "Fibrinogênio (Fibrin)": { defaultUnit: "mg/dL", referenceRange: { general: "200 - 400 mg/dL" }, inputType: "text" },
    "Tireoglobulina (TG)": { defaultUnit: "ng/mL", referenceRange: { general: "< 33 ng/mL" }, inputType: "text" },
    "Anticorpos Anti-Tireoglobulina (Anti-TG)": { defaultUnit: "UI/mL", referenceRange: { general: "< 40 UI/mL" }, inputType: "text" },
    "Homocisteína (Hcy)": { defaultUnit: "µmol/L", referenceRange: { general: "4 - 15 µmol/L" }, inputType: "text" },
    "Procalcitonina (PCT)": { defaultUnit: "ng/mL", referenceRange: { general: "< 0.05 ng/mL" }, inputType: "text" },
    "Cobre (Cu)": { defaultUnit: "µg/dL", referenceRange: { general: "70 - 140 µg/dL" }, inputType: "text" },
    "Amônia (NH3)": { defaultUnit: "µmol/L", referenceRange: { general: "18 - 72 µmol/L" }, inputType: "text" },
    "Cálcio Iônico (Ca Iônico)": { defaultUnit: "mmol/L", referenceRange: { general: "1.12 - 1.32 mmol/L" }, inputType: "text" },
    "Hepatite A IgM (Anti-HAV IgM)": { defaultUnit: "N/A", referenceRange: { general: "Não Reagente" }, inputType: "select", options: ["Não Reagente", "Reagente"] },
    "Hepatite A IgG (Anti-HAV IgG)": { defaultUnit: "N/A", referenceRange: { general: "Não Reagente" }, inputType: "select", options: ["Não Reagente", "Reagente"] },
    "Insulina (Ins)": { defaultUnit: "µUI/mL", referenceRange: { general: "2.6 - 24.9 µUI/mL" }, inputType: "text" },
    "Glicosilada (Hemoglobina Glicada, HbA1c)": { defaultUnit: "%", referenceRange: { general: "< 5.7%" }, inputType: "text" },
    "Cadeias Leves Kappa e Lambda (Cadeias Leves)": { defaultUnit: "N/A", referenceRange: { general: "Varia" }, inputType: "text" },
    "Meta-Hemoglobina (MetHb)": { defaultUnit: "%", referenceRange: { general: "< 1.5%" }, inputType: "text" },
    "Pesquisa de Criptococos (Tinta da China)": { defaultUnit: "N/A", referenceRange: { general: "Negativa" }, inputType: "select", options: ["Negativa", "Positiva"] },
    "Coombs Direto (CD)": { defaultUnit: "N/A", referenceRange: { general: "Negativo" }, inputType: "select", options: ["Negativo", "Positivo"] },
    "Coombs Indireto (CI)": { defaultUnit: "N/A", referenceRange: { general: "Negativo" }, inputType: "select", options: ["Negativo", "Positivo"] },
    "Glicemia de Jejum (GJ)": { defaultUnit: "mg/dL", referenceRange: { general: "< 99 mg/dL" }, inputType: "text" },
    "Glicemia Pós-Prandial (GPP)": { defaultUnit: "mg/dL", referenceRange: { general: "< 140 mg/dL" }, inputType: "text" },
"Grupo Sanguíneo (Tipagem)": { defaultUnit: "", referenceRange: { general: "Variável" }, inputType: "text" },

};
